### ISSUE TITLE
Trying to get in touch

### ISSUE THREAD

**Issue by joel-lobo** [medhanu/cli-blog#1]
Hey Dhananjay,

Hope you're doing well. Thanks for resolving the issues marked by Rahul on Github.

We would like to meet you in person with regards to your application for the role of Linux System Admin,tried to get in touch with you on the number you shared, although unable to connect. Please share your updated mobile number.

Please suggest a convenient time when you can do so in the coming week. Also note, our office timings are from 10:30 a.m. to 7:30 p.m. and we do not work on weekends. Please try to choose a time slot accordingly.

Looking forward to your revert.

Regards,
Joel Lobo

**Comment by medhanu** [comment]
Hi Joel,

I have replied to your email.

Best Regards,
Dhananjay.
